#  description: 
#    Adds a 2G ramdisk to be used by etcd and mounts it under /var/lib/etcd
kind: MachineConfig
apiVersion: machineconfiguration.openshift.io/v1
metadata:
  name: etcd-on-ramfs
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=Mount etcd as a ramdisk
            Before=local-fs.target
            [Mount]
            What=none
            Where=/var/lib/etcd
            Type=tmpfs
            Options=size=2G
            [Install]
            WantedBy=local-fs.target
          name: var-lib-etcd.mount
          enabled: true
